name: Performance Monitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g lighthouse

    - name: Run Lighthouse Performance Audit
      run: |
        lighthouse https://nellie00.github.io --output json --output html --output-path ./lighthouse-report.html
      continue-on-error: true

    - name: Upload Lighthouse Report
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-report
        path: ./lighthouse-report.html
